// <auto-generated />
namespace BethanyPieShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingOnePropertityinRegister : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingOnePropertityinRegister));
        
        string IMigrationMetadata.Id
        {
            get { return "202008251530302_Adding One Propertity in Register"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
