// <auto-generated />
namespace BethanyPieShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreatingProductDetailTableandAddingSomeAnnotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatingProductDetailTableandAddingSomeAnnotations));
        
        string IMigrationMetadata.Id
        {
            get { return "202008251542219_Creating ProductDetail Table and Adding Some Annotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
