// <auto-generated />
namespace MVCAppWithAuthentication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingMin18YrsIfMemberPoCoValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingMin18YrsIfMemberPoCoValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "202009020520103_adding Min18YrsIfMember PoCo Validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
